services:

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/apache-php/Dockerfile
    container_name: php-backend
    volumes:
      - ${BACKEND_DIRECTORY}:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/node/Dockerfile
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ${FRONTEND_DIRECTORY}:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    entrypoint: sh -c "npm install && npm run dev"


  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  mysql: